spring:
  redis:
    timeout: ${REDIS_TIMEOUT:2000}
    host: ${REDIS_URL:127.0.0.1}
    port: ${REDIS_PORT:19379}
    password: ${REDIS_PASSWORD:bNpPWXwAZxAda6nhtGB3t}
    database: 0
    lettuce:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 15
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 15