# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

spring:
  application:
    name: ${APPLICATION_NAME:springboot-custom-actuator}


#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"


management:
  endpoints:
    web:
      exposure:
        include: health,info,customEndpoint


  endpoint:
    health:
      show-details: always


