# 开发环境配置
server:
  port: 8081
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

spring:
  application:
    name: springboot-sentinel
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
    compatibility-verifier:
      enabled: false

